name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile Notebook
        run: |
          typst compile main.typ --font-path ./assets/fonts/
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: notebook
          path: main.pdf
