name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install cargo-hack from crates.io
        uses: baptiste0928/cargo-install@v2
        with:
          crate: typst
          git: https://github.com/typst/typst
          tag: 0.6.0

      - name: Install Fonts
        run: |
          ls ./assets/fonts/
          whoami
          pwd
          cp ./assets/fonts/* $HOME/.local/share/fonts/ 
          fc-cache -f -v
          typst fonts
      - name: Typst
        uses: lvignoli/typst-action@v0
        with:
          source_file: |
            main.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: notebook
          path: main.pdf
