name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Fonts
        run: echo "installing fonts"
        run: cp assets/fonts/* /usr/share/fonts/
      - name: Typst
        uses: lvignoli/typst-action@v0
        with:
          source_file: |
            main.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: notebook
          path: main.pdf
